apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: prod

images:
  - name: gcr.io/env-service-304211/env-service
    newName: gcr.io/env-service-304211/env-service
    newTag: b257ad9ab8fd1c344a3574d1f51c782aab0ac0d9