apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base

namespace: prod

configMapGenerator:
  - name: consumer-config
    behavior: merge
    literals:
      - GCP_PROJECT=prod-env
      - PG_USER=prod

images:
  - name: gcr.io/shared-vpc-host-multi-c103/env-service
    newName: gcr.io/shared-vpc-host-multi-c103/env-service
    newTag: 4107a1fbc68d5f4260670d472293771bc94f71f0