apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base

namespace: prod

configMapGenerator:
  - name: consumer-config
    behavior: merge
    literals:
      - PG_USER=prod

images:
  - name: gcr.io/env-service-304211/env-service
    newName: gcr.io/env-service-304211/env-service
    newTag: e84aceeadbc009b1a19f7bfef63c18f13819f605