apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base

namespace: moses-env

configMapGenerator:
  - name: consumer-config
    behavior: merge
    literals:
      - PG_USER=moses
