apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      run: consumer
  replicas: 1
  template:
    metadata:
      labels:
        run: consumer
    spec:
      containers:
      - name: consumer
        image: gcr.io/shared-vpc-host-multi-c103/env-service:dummy
        envFrom:
          - configMapRef:
              name: consumer-config
#        env:
#          - name: PUBSUB_SUBSCRIPTION
#            value: "payment-event"
#          - name: PUBSUB_TOPIC
#            value: "payment-event"
#          - name: PG_HOST
#            value: "10.162.0.3"
        resources:
          limits:
            memory: "100Mi"
            cpu: "1"
          requests:
            cpu: "0.1"
            memory: "10Mi"