apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      run: consumer
  replicas: 1
  template:
    metadata:
      labels:
        run: consumer
    spec:
      serviceAccountName: ksa
      containers:
      - name: consumer
        image: gcr.io/env-service-304211/env-service:e84aceeadbc009b1a19f7bfef63c18f13819f605
        envFrom:
          - configMapRef:
              name: gcp-config
          - configMapRef:
              name: consumer-config
        resources:
          limits:
            memory: "100Mi"
            cpu: "1"
          requests:
            cpu: "0.1"
            memory: "10Mi"