# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   annotations:
#     iam.gke.io/gcp-service-account: tf-gke-gke-on-vpc-clus-rpum@shared-vpc-host-yarel2-ac62.iam.gserviceaccount.com
#   name: ksa