apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moses-env
spec:
  destination:
    name: ''
    namespace: moses-env
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/overlays/personal/moses
    repoURL: 'https://github.com/yarelm/env-demo'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: david-env
spec:
  destination:
    name: ''
    namespace: david-env
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/overlays/personal/david
    repoURL: 'https://github.com/yarelm/env-demo'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false